### ISSUE TITLE
Error during upload

### ISSUE THREAD

**Issue by SuNounix** [YunoHost-Apps/wikijs_ynh#175]
I can't upload file when i add a media in a page.
I have an error : "Error during upload"
![Firefox_Screenshot_2022-04-11T10-08-50 080Z](https://user-images.githubusercontent.com/91945628/162716919-c475f376-4159-4651-b59b-e5493c05e524.png)

Nginx says :
[error] 22015#22015: *54396 connect() failed (111: Connection refused) while connecting to upstream, client: *xxx.xxx.xxx.xxx*, server: wiki.*domain.net*, request: "POST /u HTTP/2.0", upstream: "http://[::1]:8100/u", host: "wiki.*domain.net*", referrer: "https://wiki.domain.net/e/fr/admin/page1"

Thanks for your help.

**Comment by Serizao** [comment]
Hello, i have the same bug i try to use 127.0.0.1 instead of localhost in Nginx conf. Result is no more errore but upload not work better.

**Comment by yalh76** [comment]
well, if it works now, we can close that issue ?

**Comment by Serizao** [comment]
If your are interresting, I have solve this case : https://github.com/YunoHost-Apps/wikijs_ynh/issues/178
