### ISSUE TITLE
fresh installation no defaut storage set

### ISSUE THREAD

**Issue by prysme01** [YunoHost-Apps/wikijs_ynh#33]
Fresh installation of wikijs on a fresh yunohost installation, I can create page, but the page is not saved as there is no local storage set in the parameter.

What should I put as a local storage path ?

**Comment by yalh76** [comment]
Hi @prysme01,
There is no need for local storage. Pages are saved in the PostgreSQL database.

The local storage is an additional way to store content. Wikijs can also store content on git. But the content is always saved in the PostgreSQL database.

I think you problem is not related to local storage.
Have you tried to flush cache and cookies from your navigator ?

**Comment by prysme01** [comment]
yes I try to flush the cache, same behavior.

When i created a new page I see a root folder and file A,B,C,D, I can't create a directory, I can simply add a name to my new file and create the page perfectly, but then I can't get my page back. It is like it is not saved.

**Comment by yalh76** [comment]
Have you tried to disable local storage ?
Are you able to send me an access to your wikijs (you can send me a direct message) ?

**Comment by yalh76** [comment]
I let you try with the new version of Wikijs 2.0.0-beta.68
