### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by alexbogus** [YunoHost-Apps/wikijs_ynh#42]
After install the Wikijs app for Yunohost I have a **502 bad gateway**
Seeing the logs, I can figure that there is an error with the database "_Database Initialization Error: password authentication failed for user "wikijs_"

For debug here is the log, and the Yunohost information (for confidentiality my domain has been renamed to portal.mydomain.tld):

- yunohost 3.5.0.2 (testing)
- Destination domain for wikijs: wiki.mydomain.tld

`mar 23 23:38:08 portal.mydomain.tld systemd[1]: wikijs.service: Failed with result 'exit-code'.
mar 23 23:38:08 portal.mydomain.tld systemd[1]: wikijs.service: Unit entered failed state.
mar 23 23:38:08 portal.mydomain.tld systemd[1]: Failed to start wikijs service.
mar 23 23:38:08 portal.mydomain.tld systemd[1]: wikijs.service: Start request repeated too quickly.
mar 23 23:38:08 portal.mydomain.tld systemd[1]: Stopped wikijs service.
mar 23 23:38:08 portal.mydomain.tld systemd[1]: wikijs.service: Service hold-off time over, scheduling restart.
mar 23 23:38:08 portal.mydomain.tld systemd[1]: wikijs.service: Failed with result 'exit-code'.
mar 23 23:38:08 portal.mydomain.tld systemd[1]: wikijs.service: Unit entered failed state.
mar 23 23:38:08 portal.mydomain.tld systemd[1]: wikijs.service: Main process exited, code=exited, status=1/FAILURE
mar 23 23:38:08 portal.mydomain.tld node[4342]: 2019-03-23T22:38:08.617Z [MASTER] error: Database Initialization Error: password authentication failed for user "wikijs"
mar 23 23:38:08 portal.mydomain.tld node[4342]: 2019-03-23T22:38:08.171Z [MASTER] info: =======================================
mar 23 23:38:08 portal.mydomain.tld node[4342]: 2019-03-23T22:38:08.171Z [MASTER] info: = Wiki.js 2.0.0-beta.68 ===============
mar 23 23:38:08 portal.mydomain.tld node[4342]: 2019-03-23T22:38:08.167Z [MASTER] info: =======================================
mar 23 23:38:08 portal.mydomain.tld node[4342]: Loading configuration from /var/www/wikijs/config.yml... OK
mar 23 23:38:07 portal.mydomain.tld systemd[1]: Started wikijs service.
mar 23 23:38:07 portal.mydomain.tld systemd[1]: Stopped wikijs service.
mar 23 23:38:07 portal.mydomain.tld systemd[1]: wikijs.service: Service hold-off time over, scheduling restart.
mar 23 23:38:07 portal.mydomain.tld systemd[1]: wikijs.service: Failed with result 'exit-code'.
mar 23 23:38:07 portal.mydomain.tld systemd[1]: wikijs.service: Unit entered failed state.
mar 23 23:38:07 portal.mydomain.tld systemd[1]: wikijs.service: Main process exited, code=exited, status=1/FAILURE
-- Logs begin at Sat 2019-03-23 23:33:14 CET, end at Sat 2019-03-23 23:42:36 CET. --
[93m[1m[WARN][0m Please find here an extract of the end of the log of the service wikijs:
[93m[1m[WARN][0m The service wikijs didn't fully started before the timeout.
Please wait, the service wikijs is starting..........................................................................................................................................................................................................................................................................................................
Start the service wikijs
Reloading nginx web server...
Configuring SSOwat ...
Configuring log rotation ...
Configuring ssowat ...
Created symlink /etc/systemd/system/multi-user.target.wants/wikijs.service → /etc/systemd/system/wikijs.service.
Configuring a systemd service ...
Configuring php-fpm ...
Configuring system user ...
Reload the service nginx
Configuring nginx web server...
Setting up source files ...
ERROR: role "wikijs" does not exist
Creating a PostgreSQL database...
Installation of N - Node.js version management
Installing dependencies...
Configuring firewall ...
Storing installation settings...
Validating installation parameters...
Installing application wikijs…`

Thanks in advance
Kind regards

**Comment by yalh76** [comment]
Hi @alexbogus, 

Maybe the error come from yunohost 3.5.0.2 and his way to manage PostgreSQL.

Can you reinstall wikijs_ynh from the command line using:
`yunohost app install https://github.com/YunoHost-Apps/wikijs_ynh --debug`
and provide the complete log

**Comment by alexbogus** [comment]
Hi yalh76

Thanks for the support. The entire log is in this URL (too large to paste here)
[Complete Log](https://paste.yunohost.org/eyukanobep.sql)

Thanks again for your support
Kind regards

**Comment by yalh76** [comment]
Seems that wiki.js doesn't start and seems related to a PostgreSQL authentication error.

It's now solved, if you can try to install wiki.js and let me know if it works.

**Comment by alexbogus** [comment]
First, sorry for the delay in my reply
Thanks for your support, know is working fine! 

`160804 INFO Installation of wikijs completed
161056 SUCCESS The SSOwat configuration has been generated
161057 SUCCESS Installation complete
`
Kind regards
Alex

**Comment by yalh76** [comment]
No problems, happy to see someone using it ^^
I package it because I wanted a wiki using markdown.
But it's still a Beta version, evolving quicly :)
