### ISSUE TITLE
Git storage setup

### ISSUE THREAD

**Issue by stilobique** [YunoHost-Apps/wikijs_ynh#62]
Hello,
i want use the Git storage, i need to generate an SSH key, however, i don't know where i can store my key. If i'm read the [Wiki Js documentation](https://docs-beta.requarks.io/storage/git), it's write to use a path accessible by Wiki Js, but i don't know a good path to store this key.

When prompted to save the generated file, enter a path which can be accessed by Wiki.js `/etc/wiki/github.pem`

**Comment by yalh76** [comment]
Hi @stilobique 

`/etc/wiki/` seems like a good place. You just have to create the folder and give rights to the wiki.js user.

**Comment by stilobique** [comment]
Hum alright, the data folder work correctly -i think, i'm generate a SSH key -but with my admin user account- and Wiki Js give an error. I don't what look to fix this error. [I'm look this log](https://paste.yunohost.org/coquyucaja), but i don't see an specific error `Connection refused` and `graphql`.

`fatal: Ni ceci ni aucun de ses répertoires parents n'est un dépôt git : .git `

**Comment by yalh76** [comment]
Are you sure of the url for the git repository ?
Have you tested it manually ?
