### ISSUE TITLE
Upgrade to version 2.1.107 failed, because the wiki.js source not found.

### ISSUE THREAD

**Issue by MidAutumnMoon** [YunoHost-Apps/wikijs_ynh#91]
I found the release of version 2.1.107 was deleted from the Wiki.js repo, so the upgrading failed. :joy: 

_BTW, the latest version is 2.1.113._

Thank you.

**Comment by yalh76** [comment]
arf :/ well there already a PR to 2.1.112 #90, I will move it to 1.1.113

**Comment by MidAutumnMoon** [comment]
This update came out with many features and bug fixing I'm waiting for a long time. I cannot wait to upgrade my Wiki.js instance. :smiley:

Best wises.

**Comment by yalh76** [comment]
What kind of features are you waiting ?

**Comment by MidAutumnMoon** [comment]
@yalh76 Many！ Like with this version I can delete orphaned tags and visualize my pages as a tree.  I'm glad these useful features are finally implemented.
