### ISSUE TITLE
Ui overlap

### ISSUE THREAD

**Issue by stilobique** [YunoHost-Apps/wikijs_ynh#98]
Hello,
i'm open a small issue, the Yunohost interface overlap the edit button. Not a primodial issue, but i don't know if i need to open a ticket on Yunohost or here.

Thanks for your work ! 

![firefox_ayyq83SdjX](https://user-images.githubusercontent.com/3066684/77827900-97e8ed80-7118-11ea-9796-41114b15a082.png)

**Comment by yalh76** [comment]
You know that you can move the YunoHost button ?

**Comment by stilobique** [comment]
Yes, but no way to save a postion with an apps ?

**Comment by yalh76** [comment]
I don't know :/ maybe you should ask in the forum or in the Yunohost support channel

**Comment by stilobique** [comment]
Allright, i make that, thx for your answer ;) .

**Comment by stilobique** [comment]
I'm adding resource to explain how to fix this issue.
- https://yunohost.org/#/theming
- https://blog.genma.fr/?Yunohost-Astuce-Masquer-l-icone-en-bas-a-droite
